### DISCUSSION TITLE
How to use Block layout mode ?

### DISCUSSION THREAD

**Discussion by camcd93** [DioxusLabs/taffy#578] [Q&A] [answered]
Hi,

I'm wondering how to compute a layout using the Block mode instead of Flex or Grid.
My understanding is that if I have two block nodes that are siblings, it should automatically stack on each other and compute the (x,y) based off this. 

<img width="278" alt="CleanShot 2023-11-08 at 21 10 03@2x" src="https://github.com/DioxusLabs/taffy/assets/4093969/0e4aab6c-3b1c-445d-89b6-82c0b4566492">

When adding nodes to a Taffy tree though, the only options I get are Display::Grid, Display::Flex, or Display::None.

```rs
.new_leaf(Style { 
  display: Display::Block, // Not an option ? 
 ..Default::default()
});
```

Thanks in advance.

**Comment by camcd93** [comment]
I did notice Taffy does have Display::Block in source and should be enabled by default or with the [block_layout](https://github.com/DioxusLabs/taffy/blob/1876f72bee5e376023eaa518aa7b8a34c769bd1b/Cargo.toml#L25C1-L25C8) feature.

Setup a new project from scratch with just taffy installed (version 0.3.18), but when trying to use the "block_layout" feature, I'm getting an error from cargo saying it doesn't exist.

Cargo.toml:
```toml
[package]
name = "throwaways"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taffy = { version = "0.3.18", features = ["block_layout"] }
```

Error:
```
the package `throwaways` depends on `taffy`, with features: `block_layout` but `taffy` does not have these features.
```

Could also just be a skill issue and would appreciate some help.
