### ISSUE TITLE
Fix CI jobs running twice for PRs

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#215]
## What problem does this solve or what need does it fill?

Currently, the CI jobs will often run twice in PRs: Once for the PR and once for the push.
This is a waste of time and computing power.

## What solution would you like?

We can prevent this by changing the CI configuration to the following:

```yml
on:
  pull_request:
  push:
    branches:
      - main
```

This way, the CI only runs once for PRs, but also on `main` again to confirm that the merge didn't break anything.
